// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    // Start of learn-game-minecraft sidebar
    minecraftSidebar: [
        {
            id: 'learn-game-minecraft/getting-started',
            type: 'doc',
            label: 'Getting Started with this Guide',
        },
        {
            type: 'category',
            label: '1. Introduction to Minecraft',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-1' }],
        },
        {
            type: 'category',
            label: '2. Starting Out in Survival Mode',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-2' }],
        },
        {
            type: 'category',
            label: '3. Advanced Survival Skills',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-3' }],
        },
        {
            type: 'category',
            label: '4. Mastering Construction and Architecture',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-4' }],
        },
        {
            type: 'category',
            label: '5. Introduction to Redstone',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-5' }],
        },
        {
            type: 'category',
            label: '6. The World of Enchanting and Potions',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-6' }],
        },
        {
            type: 'category',
            label: '7. Exploration and The End',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-7' }],
        },
        {
            type: 'category',
            label: '8. Creative Mode and Artistic Builds',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-8' }],
        },
        {
            type: 'category',
            label: '9. Multiplayer and Servers',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-9' }],
        },
        {
            type: 'category',
            label: '10. Modding and Custom Content',
            items: [{ type: 'autogenerated', dirName: 'learn-game-minecraft/module-10' }],
        },
    ],
    // End of learn-game-minecraft sidebar

};

module.exports = sidebars;